services:
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: sstsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - ssts-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sstsdb"]
      interval: 5s
      timeout: 2s
      retries: 20

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env.prod
    networks:
      - ssts-network
    command: node dist/index.js

  deploy:
    image: api
    profiles: ["deploy"]
    command: sh -c "npx prisma migrate deploy && npx prisma generate"
    env_file:
      - .env.prod
    networks:
      - ssts-network
    depends_on:
      postgres_db:
        condition: service_healthy

  seed:
    image: api
    profiles: ["seed"]
    command: npx prisma db seed
    env_file:
      - .env.prod
    networks:
      - ssts-network
    depends_on:
      postgres_db:
        condition: service_healthy

networks:
  ssts-network:
    name: ssts-network
